import Head from 'next/head'

export default props => {

  const {
    title
  } = props;
  
  return (
    <Head>
        {<title>{title || "Expat-ations"}</title>}
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/plane-solid.svg" />
        <script src="https://cdn.tailwindcss.com"></script>
        <script
          src="https://kit.fontawesome.com/c3b30720d4.js"
          crossorigin="anonymous"
        ></script>
        {props.children}
    </Head>
  )
}
