import Head from "next/head";
import HeroSection from "../components/HeroSection"
import Heading from "../components/Heading";
import Footer from "../components/Footer";
import NavBar from "../components/NavBar";
import CurrencyConverter from "../components/CurrencyConverter";
import Link from "next/link";
import SearchField from "../components/SearchField"; 

export async function getStaticProps() {
  const cities = [];
  const res = await fetch("https://api.teleport.org/api/urban_areas/");
  const data = await res.json();

  data._links["ua:item"].forEach((city) => cities.push(city.name));

  return {
    props: {
      city_list: cities,
    },
  };
}

export default function Home({ city_list }) {

  const navigate = () => {

  }

  return (
    <>
      <Head>
        <title>Expat-ations</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/plane-solid.svg" />
        <script src="https://cdn.tailwindcss.com"></script>
      </Head>
      <NavBar className={"bg-transparent shadow-none text-3xl"} />

      <HeroSection />

      <div
        className=" flex flex-col justify min-h-screen bg-fixed bg-center bg-cover"
        style={{
          background: `linear-gradient(to bottom, #2d334a, #bae8e8, #e3f6f5)`,
        }}
      >

          <Heading cities={city_list} />

          <Link
            className="bg-blue-500 text-white px-4 py-2 rounded-lg shadow hover:bg-blue-600 active:bg-blue-800 focus:outline-none focus:ring-2 focus:ring-blue-300 focus:ring-opacity-50"
            href = "/city"
          > 
            Chat-GPT 
          </Link>
 
        
      </div>

      <div class="flex flex-row justify-center">
        <CurrencyConverter />
      </div>
      <Footer />
    </>
  );
}
